version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    volumes:
      - ./:/var/www/html
    networks:
      - my_network2

networks:
  my_network2:
    driver: bridge